### PR TITLE
fix: uid not found

### LINKED ISSUE #167: Prover doesn't recognize UID object from sui::object
Image

Prover run fails with issues UID type exported from sui::object is not found, however contracts build successfully.

`use sui::object::{UID, ID};`

Reference to codebase for testing given case shared internaly.

### PR DESCRIPTION
**Pull request by d3mage**
Fixes #167

### CODE REVIEW

File: crates/move-stackless-bytecode/src/dynamic_field_analysis.rs [hunk 1]
```diff
@@ -458,6 +459,12 @@ impl FunctionTargetProcessor for DynamicFieldAnalysisProcessor {
             return data;
         }
 
+        let info = get_info(&FunctionTarget::new(&fun_env, &data));
+        if !info.verified || !info.inlined {
```
Comment (andreistefanescu) [inline crates/move-stackless-bytecode/src/dynamic_field_analysis.rs:463]: this is incorrect, as it skips functions that are not both `inlined` and `verified`. it should be `!info.verified && !info.inlined`
